import { StyleSheet } from 'react-native';

export const polinizacionesStyles = StyleSheet.create({
  // ESTILOS PRINCIPALES
  mainContainer: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },

  // ESTILOS DEL HEADER
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
    marginTop: 20,
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 36,
    fontWeight: '900',
    color: '#182d49',
    letterSpacing: -0.8,
    lineHeight: 44,
  },
  subtitle: {
    fontSize: 18,
    color: '#6b7280',
    marginTop: 8,
    fontWeight: '500',
    lineHeight: 26,
  },
  addButton: {
    backgroundColor: '#e9ad14',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#d4a017',
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 3,
  },

  // ESTILOS DE ACCIONES ADICIONALES
  actionsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 32,
    paddingHorizontal: 4,
  },
  actionButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    flex: 1,
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#6b7280',
    fontWeight: '700',
    fontSize: 15,
  },

  // ESTILOS DE FILTROS
  filtersRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  filterButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    minWidth: 140,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  filterButtonActive: {
    borderColor: '#e9ad14',
    backgroundColor: '#fef9e7',
  },
  filterButtonText: {
    color: '#6b7280',
    fontWeight: '700',
    fontSize: 14,
  },
  filterButtonTextActive: {
    color: '#e9ad14',
    fontWeight: '800',
  },

  // ESTILOS DE LA LISTA
  list: {
    flex: 1,
  },

  // ESTILOS DE LAS TARJETAS
  polinizacionCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  cardHeader: {
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  codigoText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#182d49',
    letterSpacing: -0.5,
    flex: 1,
  },
  tipoBadge: {
    backgroundColor: '#e9ad14',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 24,
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  tipoBadgeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  cardContent: {
    flexDirection: 'row',
    gap: 24,
  },
  leftContent: {
    flex: 1,
    gap: 12,
  },
  especieGenero: {
    fontSize: 20,
    fontWeight: '800',
    color: '#182d49',
    marginBottom: 16,
    lineHeight: 28,
  },
  infoText: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 6,
    fontWeight: '600',
    lineHeight: 22,
  },
  rightContent: {
    alignItems: 'center',
    gap: 20,
    minWidth: 140,
  },
  procesoLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#6b7280',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  horizontalProcessLine: {
    flexDirection: 'row',
    gap: 20,
  },
  processStep: {
    alignItems: 'center',
    gap: 8,
  },
  processStepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#e5e7eb',
  },
  processStepCircleActive: {
    backgroundColor: '#e9ad14',
    borderColor: '#d4a017',
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  processStepCircleCompleted: {
    backgroundColor: '#10b981',
    borderColor: '#059669',
  },
  processStepText: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
    fontWeight: '700',
    maxWidth: 70,
    lineHeight: 16,
  },
  processStepTextActive: {
    color: '#182d49',
    fontWeight: '800',
  },

  // ESTILOS DE CARGA
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    paddingVertical: 100,
  },
  loadingText: {
    marginTop: 24,
    fontSize: 20,
    color: '#6b7280',
    fontWeight: '700',
  },

  // ESTILOS DE ESTADO VACÍO
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#6b7280',
    marginBottom: 16,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 18,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 28,
    fontWeight: '600',
  },

  // ESTILOS DEL MODAL
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 28,
    margin: 20,
    maxHeight: '85%',
    minWidth: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 15,
  },
  detalleTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#182d49',
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: -0.8,
  },
  detalleContent: {
    maxHeight: 400,
  },
  detalleRow: {
    flexDirection: 'row',
    marginBottom: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  detalleLabel: {
    fontWeight: '800',
    color: '#182d49',
    width: 140,
    fontSize: 16,
  },
  detalleValue: {
    flex: 1,
    color: '#6b7280',
    fontSize: 16,
    fontWeight: '600',
  },
  closeButton: {
    backgroundColor: '#e9ad14',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 16,
    marginTop: 24,
    alignItems: 'center',
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },

});
