import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  centered: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 8,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 28,
    shadowColor: '#4a6cf7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#e0e7ff',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#4a6cf7',
    marginBottom: 24,
    textAlign: 'center',
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f4ff',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  infoText: {
    fontSize: 13,
    color: '#4338ca',
    marginLeft: 8,
    flex: 1,
    lineHeight: 18,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#182d49',
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: '#e0e7ff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 16,
    backgroundColor: '#f7f9fc',
    color: '#222',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#e0e7ff',
    borderRadius: 8,
    marginBottom: 16,
    backgroundColor: '#f7f9fc',
  },
  button: {
    backgroundColor: '#4a6cf7',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#4a6cf7',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },

  // Estilos para la predicción
  prediccionContainer: {
    backgroundColor: '#f8fafc',
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    marginTop: 8,
  },
  prediccionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  prediccionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4a6cf7',
    marginLeft: 8,
    flex: 1,
  },
  refreshButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  loadingText: {
    marginTop: 8,
    color: '#6b7280',
    fontSize: 14,
  },
  prediccionContent: {
    gap: 12,
  },
  prediccionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  prediccionItem: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  prediccionLabel: {
    fontSize: 12,
    color: '#6b7280',
    marginBottom: 4,
    fontWeight: '500',
  },
  prediccionValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  prediccionFecha: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1fae5',
  },
  fechaEstimada: {
    marginLeft: 8,
    fontSize: 14,
    color: '#065f46',
    fontWeight: '600',
  },
  prediccionTipo: {
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  tipoPrediccion: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '500',
  },
  siguientePaso: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#eff6ff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  siguientePasoText: {
    marginLeft: 8,
    fontSize: 13,
    color: '#1e40af',
    fontWeight: '500',
    flex: 1,
    lineHeight: 18,
  },
  errorText: {
    color: '#dc2626',
    fontSize: 14,
    textAlign: 'center',
    fontStyle: 'italic',
  },

  // Estilos para la sección de predecir tiempo
  prediccionTiempoContainer: {
    backgroundColor: '#f0fdf4',
    borderWidth: 2,
    borderColor: '#bbf7d0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    marginTop: 8,
  },
  prediccionTiempoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  prediccionTiempoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#10b981',
    marginLeft: 8,
  },
  prediccionTiempoDesc: {
    fontSize: 14,
    color: '#065f46',
    marginBottom: 16,
    lineHeight: 20,
  },
  tiempoFieldsContainer: {
    gap: 16,
    marginBottom: 16,
  },
  tiempoRow: {
    flexDirection: 'row',
    gap: 12,
  },
  tiempoField: {
    flex: 1,
  },
  tiempoFieldFull: {
    flex: 1,
  },
  tiempoLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#047857',
    marginBottom: 6,
  },
  tiempoInput: {
    borderWidth: 1,
    borderColor: '#d1fae5',
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#ffffff',
    fontSize: 14,
    color: '#111827',
  },
  tiempoPickerContainer: {
    borderWidth: 1,
    borderColor: '#d1fae5',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  predecirButton: {
    backgroundColor: '#10b981',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    borderRadius: 8,
    gap: 8,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  predecirButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  predecirButtonDisabled: {
    backgroundColor: '#9ca3af',
    shadowOpacity: 0,
    elevation: 0,
  },
  predecirHelpText: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
});
