import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    backgroundColor: '#f7f8fa',
    minHeight: '100%',
    paddingVertical: 32,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f7f8fa',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 32,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  logo: {
    fontSize: 44,
    fontWeight: 'bold',
    color: '#182d49',
    marginBottom: 6,
    letterSpacing: 1.5,
    textShadowColor: '#e9ad14',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  ecuagenera: {
    color: '#e9ad14',
    fontWeight: 'bold',
    fontSize: 20,
    letterSpacing: 3,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(25,45,73,0.10)',
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 4,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 18,
    color: '#121212',
    fontWeight: '500',
    marginBottom: 4,
  },
  formContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: '#fff',
    padding: 32,
    borderRadius: 18,
    shadowColor: '#182d49',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#e1e1e1', // gris claro
  },
  inputContainer: {
    marginBottom: 18,
  },
  label: {
    fontSize: 15,
    color: '#182d49',
    marginBottom: 7,
    marginLeft: 4,
    fontWeight: '600',
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: '#e1e1e1', // gris claro
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 16,
    backgroundColor: '#fff',
    color: '#121212',
    fontWeight: '500',
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  button: {
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#182d49',
    marginTop: 10,
    shadowColor: '#e9ad14',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    width: '100%',
    paddingHorizontal: 0,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 28,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#e1e1e1', // gris claro
  },
  footerText: {
    color: '#121212',
    fontSize: 15,
    fontWeight: '500',
  },
  footerLink: {
    color: '#e9ad14', // dorado solo en el link
    fontWeight: '700',
    fontSize: 15,
    textDecorationLine: 'underline',
    marginLeft: 2,
  },
});
